### ISSUE TITLE
Target Warframe app window

### ISSUE THREAD

**Issue by telorand** [thewhiteserpent/JARRS#1]
Add the ability to send the recruiting message to the Warframe window if:

- It's in the background
- Recruiter chat is open

There's no way to check that recruiter chat is open, so if we can get this working, we should warn the user in the documentation.

**Comment by Alchemishty** [comment]
Added best of what's viable: The recruiting messages turn off as soon as the Warframe window becomes inactive. Need conformation on its successful working.
